---

# ansible-playbook -i inventory collect-package-facts.yml -vv

- hosts: all
  gather_facts: True
  tasks:
    - name: "get package facts"
      package_facts:
        manager: auto

    - name: "list package facts"
      debug:
        msg: "{{ ansible_facts.packages }}"
